export const state = {
    LOBBY: 'LOBBY',
    CONDUCTOR_GROUP_SETUP: 'CONDUCTOR_GROUP_SETUP',
    MUSICIAN_GROUP_SETUP: 'MUSICIAN_GROUP_SETUP',
    CONDUCTOR_SONG_PLAYING: 'CONDUCTOR_SONG_PLAYING',
    MUSICIAN_SONG_PLAYER: 'MUSICIAN_SONG_PLAYER',
    SONG_COMPLETE: 'SONG_COMPLETE',
}