export const state = {
    LOBBY: 'LOBBY',
    REGISTERED: 'REGISTERED',
    REGISTER_USERNAME: 'REGISTER_USERNAME',
    NEW_VIP: 'NEW_VIP',
    EVERYBODY_READY: 'EVERYBODY_READY',
    CONDUCTOR_SETUP: 'CONDUCTOR_SETUP',
    GAME_START: 'GAME_START',
    MUSICIAN_SETUP: 'MUSICIAN_SETUP',
    CONDUCTOR_SONG_PLAYING: 'CONDUCTOR_SONG_PLAYING',
    MUSICIAN_SONG_PLAYER: 'MUSICIAN_SONG_PLAYER',
    SONG_COMPLETE: 'SONG_COMPLETE',
}